"""create_all for dev-database

Revision ID: 3cbc7fedaa12
Revises: 513a04abd036
Create Date: 2015-06-24 23:08:03.916230

"""

# revision identifiers, used by Alembic.
revision = '3cbc7fedaa12'
down_revision = '513a04abd036'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
