"""initial migration

Revision ID: 513a04abd036
Revises: None
Create Date: 2015-06-24 16:43:18.255781

"""

# revision identifiers, used by Alembic.
revision = '513a04abd036'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
