"""add photo_path and text_path to Pic table

Revision ID: a3c5127d670
Revises: None
Create Date: 2015-06-28 00:19:40.193756

"""

# revision identifiers, used by Alembic.
revision = 'a3c5127d670'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
